name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Ajuste la version selon ton projet
      - name: Configure vite
        run: |
          echo 'export default {
            base: "/${{ github.event.repository.name }}/"
          }' > vite.config.js

      - name: Créer un fichier .env
        run: |
          echo "VITE_WEATHER_API_KEY=${{ secrets.VITE_WEATHER_API_KEY }}" >> .env
          echo "VITE_PICTURES_API_KEY=${{ secrets.VITE_PICTURES_API_KEY }}" >> .env
          cat .env
          
      - name: Installer les dépendances
        run: npm install 

      - name: Construire le projet
        run: npm run build

      - name: Upload des fichiers prêts pour la production
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Télécharger l’artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist

      - name: Déployer sur GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist