name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install 

      - name: Configure vite
        run: |
          echo '
          import { defineConfig, loadEnv } from "vite"
          export default defineConfig(({ mode }) => {
            const env = loadEnv(mode, process.cwd())
            return {
              base: "/nom-du-repo/",
              define: {
                __VITE_PICTURES_API_KEY__: JSON.stringify(env.VITE_PICTURES_API_KEY),
                __VITE_WEATHER_API_KEY__: JSON.stringify(env.VITE_WEATHER_API_KEY),
              }
            }
          })
          ' > vite.config.js

      - name: Display vite.config.js file (debug)    
        run: cat vite.config.js

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
